# Create a new release with every tag push
on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: update coder template
        run: gh release create ${{ github.ref }} -t ${{ github.ref }} -n ${{ github.ref }} -R ${{ github.repository }} -p
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
