name: Release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

        # Get the version tag
      - name: Get version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

        # Create a pre release if tag name has alpha or beta
      - name: Create pre release
        if: contains(steps.get_version.outputs.VERSION , 'alpha') || contains(steps.get_version.outputs.VERSION, 'beta')
        run: gh release create ${{ github.ref }} -t ${{ github.ref_name }} --prerelease --generate-notes -R ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        # Create release
      - name: Create release
        if: !contains(steps.get_version.outputs.VERSION , 'alpha') && !contains(steps.get_version.outputs.VERSION, 'beta')
        run: gh release create ${{ github.ref }} -t ${{ github.ref_name }} --generate-notes -R ${{ github.repository }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
